Update NDVI process to use dask
SatelliteApplicationsCatapult/cubequery-deployment pull request #5
Opened 2020-04-03 10:16 UTC by dtip

See commit messages for more info.

2020-04-07 17:12 UTC, dtip commented
@emilyselwood This one's ready for you!

2020-04-08 14:28 UTC, emilyselwood requested changes

2020-04-08 14:28 UTC, emilyselwood commented on processes/ndvi_anomaly.py
> +        Parameter("crs", "CRS", DType.STRING, "CRS to use for the analysis"),
Can we rename this to AOI CRS or input CRS or something similar? Makes it clear the difference between crs and projection

2020-04-08 14:28 UTC, emilyselwood commented on processes/ndvi_anomaly.py
> +            "projection",
can we rename this to output projection. this will make it clear the difference between projection and crs

2020-04-09 07:45 UTC, emilyselwood approved these changes

2020-04-15 09:44 UTC, merged